# Generated by Django 3.1.5 on 2021-06-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_url',
            field=models.URLField(blank=True),
        ),
    ]
