# Generated by Django 3.1.5 on 2021-06-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210627_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
